# Generated by Django 3.2.13 on 2022-04-27 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loadtarget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='picture1',
            field=models.ImageField(default=None, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='target',
            name='picture2',
            field=models.ImageField(default=None, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='target',
            name='picture3',
            field=models.ImageField(default=None, upload_to='images/'),
            preserve_default=False,
        ),
    ]
