# Generated by Django 3.2.13 on 2022-04-28 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loadtarget', '0002_auto_20220427_0118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='target',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='target',
            old_name='target_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='target',
            name='picture1',
        ),
        migrations.RemoveField(
            model_name='target',
            name='picture2',
        ),
        migrations.RemoveField(
            model_name='target',
            name='picture3',
        ),
        migrations.AddField(
            model_name='target',
            name='file_location',
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
    ]
